In [1]:
import numpy  as np

In [12]:
a =np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


In [18]:
b = np.zeros([4,6])
print(b)



[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
b[2][1] = 99
print(b)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0. 99.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [21]:
arr = np.array([12,45,7,19,88,3,56,91,24,67])
c = arr> 50
print(arr[c])

[88 56 91 67]


In [22]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
d[np.diag_indices(5)] =(10,20,30,40,50)
print(d)

[[10.  0.  0.  0.  0.]
 [ 0. 20.  0.  0.  0.]
 [ 0.  0. 30.  0.  0.]
 [ 0.  0.  0. 40.  0.]
 [ 0.  0.  0.  0. 50.]]


In [28]:
x = np.arange(1,21).reshape(4,5)
print (x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [31]:
print(x[2:])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [32]:
print(x[: ,2:3])

[[ 3]
 [ 8]
 [13]
 [18]]


In [33]:
print(x[:3,:3])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [ ]:
a = np.array([1,2,3,4])
b= np.array([[10],[20],[30]])
c =a+b
print(c)
# shape will be (3,4) because:
# b (3,1) broadcasts across columns to match (3,4)
# a (4,) broadcasts across rows to match (3,4)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [37]:
data = np.array([150,220,90,300,180,45])
n = (data - data.min())/( data - data.max())
print(n)

[-0.7        -2.1875     -0.21428571         inf -1.125      -0.        ]


C:\Users\Haneen\AppData\Local\Temp\ipykernel_23072\3859560404.py:2: RuntimeWarning: divide by zero encountered in divide
  n = (data - data.min())/( data - data.max())


In [38]:
z_scores = (data - data.mean()) / data.std()
print(z_scores)

[-0.16988961  0.66956492 -0.88942206  1.62894153  0.18987662 -1.42907141]


In [ ]:
mat = np.array([[4,8,1,12],
                [7,3,9,5],
                [11,2,6,10],
                [15,0,14,13]])
row_m = mat.mean(axis=1 , keepdims= True)
print(row_m)

[[ 6.25]
 [ 6.  ]
 [ 7.25]
 [10.5 ]]


In [41]:
row_S = mat.sum(axis=0 , keepdims= True)
print(row_S)

[[37 13 30 40]]


In [43]:
max = mat.max()
print(max)

15


In [47]:
p = np.unravel_index(mat.argmax() , mat.shape)
print(p)

(np.int64(3), np.int64(0))


In [48]:
arr = np.arange(36)
re =arr.reshape(3,4,3)
print(re)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [51]:
arr = np.arange(1,17).reshape(4,4)
arr1 =arr[::-1 , ::-1]
print(arr1)

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [53]:
ages = np.array([23,45,19,34,28,51,17,39])
names = np.array(["Ali","sara","omar","lina","khaled","nour","yara","hassan"])

In [54]:
f = (ages>25) & (ages < 40)

print(names[f])

['lina' 'khaled' 'hassan']


In [55]:
ages[ages < 20] =20
print(ages)

[23 45 20 34 28 51 20 39]


In [57]:
np.random.seed(123)
arr = np.random.randint(1, 101, size=(6, 6))
print(arr)

[[ 67  93  99  18  84  58]
 [ 87  98  97  48  74  33]
 [ 47  97  26  84  79  37]
 [ 97  81  69  50  56  68]
 [  3  85  40  67  85  48]
 [ 62  49   8 100  93  53]]


In [58]:
arr = np.random.normal(loc=100, scale=15, size=10)
print(arr)

[127.06686834  85.51674961  80.25279948  90.61322265  95.09580659
  95.37686206 112.40676196 116.06172126  54.16633874 115.08897902]


In [59]:
colors = ["red", "blue", "green", "yellow", "purple"]

selected = np.random.choice(colors, size=3, replace=False)
print(selected)

['blue' 'yellow' 'purple']


In [60]:
nums = np.arange(1, 21)
np.random.shuffle(nums)
print(nums)

[14  4  1  7 13 15 16 17  9  5  3 10 18  6 11 19  2 20 12  8]
